# Generated by Django 4.2.3 on 2023-07-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_bulkemail_id_alter_cbt_id_alter_cbtq_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtq',
            name='answers',
            field=models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3'), ('Option4', 'Option4')], max_length=200),
        ),
    ]
